# Site settings
title: Dr. Nabil Imadali - Dermatologue et Centre Laser - Boumerdès
description: "Site du cabinet dermatologique du Dr. Nabil Imadali."
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the name of your domain
logo_url: svg/logo.png

# Hero
# hero: 
#     hero_img: hero.jpg
#     hero_title: Dr. Nabil Imadali - Cabinet de dermatologie - Boumerdes
#     hero_description: Site du cabinet dermatologique du Dr. Nabil Imadali.

# Contact form
api_token: # Enter API token here

# Contact info
contact:
    phone: (Demander au secrétariat)
#    emergency: 931 53 234
    email: nabil.imadali@yahoo.fr
    address: Cité 11 Decembre 1960, <br> Boumerdès - Algérie

# Opening hours
dimanche_jeudi: 9:00 – 17:00
samedi: 9:00 – 16:00
vendredi: fermeture

# Testimonials
testimonials:
    testimonials_img: parallax.jpg

# Map
map:
    zoom: 17
    address: Cité 11 Decembre 1960, Boumerdès, Algérie
    address_details: svg/min/logo.svg

# Social settings
facebook: http://facebook.com
twitter: http://twitter.com
instagram: http://instagram.com
youtube: http://youtube.com
skype: skype:obaez_design?userinfo
feed: yes

# Footer
copyright: © 2017 Sofiane and Nabil Imadali, All rights reserved. (Based on the Jekyll DentistSmile template).

# Build settings
markdown: kramdown

exclude: [
    package.json,
    Gruntfile.js,
    node_modules,
    .sass-cache,
    Gemfile,
    Gemfile.lock,
    .gitignore
]

# Theme Settings
analytics: 
google_verification:
